package com.medicconnect.config;

import com.medicconnect.utils.AuthTokenUtil;
import io.jsonwebtoken.Claims;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * JWT Authentication Filter
 * Validates login tokens generated by AuthTokenUtil and sets user context.
 */
@Component
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    private final AuthTokenUtil authTokenUtil;

    @Autowired
    public JwtAuthenticationFilter(AuthTokenUtil authTokenUtil) {
        this.authTokenUtil = authTokenUtil;
    }

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain)
            throws ServletException, IOException {

        try {
            String authHeader = request.getHeader("Authorization");

            if (authHeader != null && authHeader.startsWith("Bearer ")) {
                String token = authHeader.substring(7);

                Claims claims = authTokenUtil.validateAndGetClaims(token);
                if (claims != null && SecurityContextHolder.getContext().getAuthentication() == null) {

                    String email = (String) claims.get("email");
                    Object rolesClaim = claims.get("roles");

                    // Extract authorities from roles claim
                    List<SimpleGrantedAuthority> authorities = Collections.emptyList();
                    if (rolesClaim instanceof List<?>) {
                        authorities = ((List<?>) rolesClaim).stream()
                                .map(Object::toString)
                                .map(SimpleGrantedAuthority::new)
                                .collect(Collectors.toList());
                    }

                    User principal = new User(email, "", authorities);
                    UsernamePasswordAuthenticationToken authentication =
                            new UsernamePasswordAuthenticationToken(principal, null, authorities);

                    authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                    SecurityContextHolder.getContext().setAuthentication(authentication);
                }
            }
        } catch (Exception ex) {
            System.out.println("❌ JWT Authentication failed: " + ex.getMessage());
        }

        filterChain.doFilter(request, response);
    }
}
